### ISSUE TITLE
ReferenceError: Aliases is not defined

### ISSUE THREAD

**Issue by hkjens** [jcschmidig/plugin-resolve-alias#1]
version 1.0.5
index.js: line 12: ReferenceError: Aliases is not defined

exports.plugin = function({
    srcFilename, srcContent, devPath, extensions, **Aliases:config**, Warning })
{
   ...
    if ( !(**Aliases** || console.log("[plugin-resolve-alias] Aliases missing!")) ) return
   ...

Possible solution: line 4: change Aliases:config to Aliases

**Comment by jcschmidig** [comment]
Thanks for reporting!

**Comment by jcschmidig** [comment]
Fixed in 1.0.6
